### ISSUE TITLE
workflows "test executable help output" section has some errors

### ISSUE THREAD

**Issue by cknowles-moz** [MoCo-GHE-Admin/github-scripts#102]
While working on the nodejs updates, noticed that the `test executable help output` section of the workflow is generating a lot of import errors ... it's marking things as passed, so either the test is wrong, or the output is wrong, but "Something's weird here, can you talk a look?"  From poking, I think it's because the dependencies aren't there, but it really looks like they should be ... so we're in "cknowles-moz needs redirection/education" territory

Would love an education if/when any findings occur.

**Comment by aerickson** [comment]
The command wasn't executing in a poetry environment where the modules are installed.

The larger issue is that `find -exec` doesn't inspect the result code of the commands it's running. More info in #103.
