### ISSUE TITLE
Add security manager to orgs script

### ISSUE THREAD

**Issue by cknowles-moz** [MoCo-GHE-Admin/github-scripts#25]
Need to add a security manager to all <option for list of orgs> orgs in the <option for teamname> team.  With 50 orgs, this is a less than fun process, hence the desire to automate it.  (removal from the team may be a thing, but likely that would be with removal of the account altogether, so the remove user process would handle it)

**Comment by cknowles-admin** [comment]
@cknowles-moz testing @ callouts

**Comment by cknowles-admin** [comment]
@cknowles-moz Test2

**Comment by cknowles-admin** [comment]
test3 @cknowles-moz

**Comment by cknowles-admin** [comment]
now that we have the moco-security-manager team in the orgs, and the script ./org_comms_team.py - which can add users to a team (rename probably inbound) this can be scripted via piping and a for loop.
